# Generated by Django 3.2.4 on 2021-06-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/images')),
                ('song', models.FileField(upload_to='media/images')),
            ],
        ),
    ]
