# Generated by Django 3.2.4 on 2021-06-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeatapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
