# Generated by Django 3.2.4 on 2021-07-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeatapp', '0002_rename_songs_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='movie',
            field=models.CharField(default='', max_length=500),
        ),
    ]
