# Generated by Django 3.2.4 on 2021-07-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeatapp', '0004_carousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingSong',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/images')),
                ('song', models.FileField(upload_to='media/images')),
                ('movie', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
