# Generated by Django 3.2.4 on 2021-07-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeatapp', '0005_trendingsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingsong',
            name='image',
            field=models.ImageField(upload_to='trendingsongs/images'),
        ),
        migrations.AlterField(
            model_name='trendingsong',
            name='song',
            field=models.FileField(upload_to='trendingsongs/images'),
        ),
    ]
