# Generated by Django 3.2.4 on 2021-07-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeatapp', '0006_auto_20210706_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingsong',
            name='movie',
        ),
    ]
