# Generated by Django 3.2.4 on 2021-07-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeatapp', '0007_remove_trendingsong_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendingsong',
            old_name='image',
            new_name='trendimage',
        ),
        migrations.RenameField(
            model_name='trendingsong',
            old_name='name',
            new_name='trendname',
        ),
        migrations.RenameField(
            model_name='trendingsong',
            old_name='singer',
            new_name='trendsinger',
        ),
        migrations.RenameField(
            model_name='trendingsong',
            old_name='song_id',
            new_name='trendsong_id',
        ),
        migrations.RenameField(
            model_name='trendingsong',
            old_name='song',
            new_name='trendsonglist',
        ),
        migrations.RenameField(
            model_name='trendingsong',
            old_name='tags',
            new_name='trendtags',
        ),
    ]
