# Generated by Django 3.2.4 on 2021-07-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeatapp', '0008_auto_20210706_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingsong',
            name='trendimage',
            field=models.ImageField(upload_to='trendingsongsmedia/images'),
        ),
        migrations.AlterField(
            model_name='trendingsong',
            name='trendsonglist',
            field=models.FileField(upload_to='trendingsongsmedia/songs'),
        ),
    ]
