# Generated by Django 3.2.4 on 2021-07-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeatapp', '0009_auto_20210706_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendingsong',
            name='trendimage',
            field=models.ImageField(upload_to='trendpics/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='trendingsong',
            name='trendsonglist',
            field=models.FileField(upload_to='trendsongs/%y/%m/%d'),
        ),
    ]
