# Generated by Django 3.2.4 on 2021-07-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeatapp', '0010_auto_20210707_1028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrendingSong',
        ),
    ]
